// Copyright 2017 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_xgatt_gpio_pb0                  19
#define gattdb_xgatt_gpio_pb1                  22
#define gattdb_xgatt_gpio_led0                 25
#define gattdb_xgatt_gpio_led1                 28
#define gattdb_xgatt_gpio_PWM1                 31
#define gattdb_xgatt_gpio_uart                 34
#define gattdb_xgatt_gpio_ADC0                 37
#define gattdb_ota_control                     41

#endif
